### ISSUE TITLE
skale-api can not receive answer on `/api/v1/schains/list` request because of allocation types addition

### ISSUE THREAD

**Issue by OleksanderSalamatov** [skalenetwork/skale-admin#1124]
`skale schain ls` command in `node-cli` is broken as a result of incorrect addition of schain allocation types in `skale-api`

skale-admin: `2.8.0-beta.1`
node-cli: `2.5.0-beta.0`

Logs:

node-cli:
```
root@Regression-13:~# skale schains ls
Command failed with following errors:
--------------------------------------------------
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
--------------------------------------------------
You can find more info in /root/.skale/.skale-cli-log/debug-node-cli.log
```

skale-api:
```
[2024-10-30 15:31:40,331] 21805 INFO /api/v1/schains/list skale_base: Initing skale.py, endpoint: http://[ETH_IP]:8545, wallet: RedisWalletAdapter
[2024-10-30 15:31:40,346] 21805 INFO /api/v1/schains/list skale_manager: Debug contracts found in ABI file
[2024-10-30 15:31:40,849] ERROR in app: Exception on /api/v1/schains/list [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/admin/web/helper.py", line 92, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/admin/web/routes/schains.py", line 92, in schains_list
    schains_list = list(filter(
                   ^^^^^^^^^^^^
  File "/usr/src/admin/web/routes/schains.py", line 93, in <lambda>
    lambda s: s.get('name'),
              ^^^^^
AttributeError: 'SchainStructure' object has no attribute 'get'
[2024-10-30 15:31:40,849] 21805 ERROR /api/v1/schains/list app: Exception on /api/v1/schains/list [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/admin/web/helper.py", line 92, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/admin/web/routes/schains.py", line 92, in schains_list
    schains_list = list(filter(
                   ^^^^^^^^^^^^
  File "/usr/src/admin/web/routes/schains.py", line 93, in <lambda>
    lambda s: s.get('name'),
              ^^^^^
AttributeError: 'SchainStructure' object has no attribute 'get'
[2024-10-30 15:31:40,850] ERROR in app: Request failed with error 'SchainStructure' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/admin/web/helper.py", line 92, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/admin/web/routes/schains.py", line 92, in schains_list
    schains_list = list(filter(
                   ^^^^^^^^^^^^
  File "/usr/src/admin/web/routes/schains.py", line 93, in <lambda>
    lambda s: s.get('name'),
              ^^^^^
AttributeError: 'SchainStructure' object has no attribute 'get'
[2024-10-30 15:31:40,850] 21805 ERROR /api/v1/schains/list app: Request failed with error 'SchainStructure' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/admin/web/helper.py", line 92, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/admin/web/routes/schains.py", line 92, in schains_list
    schains_list = list(filter(
                   ^^^^^^^^^^^^
  File "/usr/src/admin/web/routes/schains.py", line 93, in <lambda>
    lambda s: s.get('name'),
              ^^^^^
AttributeError: 'SchainStructure' object has no attribute 'get'
[2024-10-30 15:31:40,851] INFO in app: Request finished 130e141c04, time elapsed: 0s
[2024-10-30 15:31:40,851] 21805 INFO /api/v1/schains/list app: Request finished 130e141c04, time elapsed: 0s

```

**Comment by OleksanderSalamatov** [comment]
Verified

skale-admin: `2.8.0-beta.2`
node-cli: `2.5.0-beta.3`

Logs:
```
root@Regression-11:~# skale schains ls
               Name                                     Owner                      Size   Lifetime        Created At        Deposit   Generation                   Originator                   Type
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
exciting-glittering-sharatan          0x47A260715623df37b9F5ea52C2E66245c0529DF2   16     43200      Oct 24 2024 11:50:24   0         2            0x0000000000000000000000000000000000000000   2   
barren-stimulating-botein             0x71cBE3fedE33905d4D1Bf2Bd51f9d4A62375e659   16     43200      Oct 21 2024 17:32:36   0         2            0x0000000000000000000000000000000000000000   2   
thirsty-miserable-hamal               0x487360568fE5Ee4AE5c75782D5F63e9935B0E512   16     43200      Oct 22 2024 11:10:36   0         2            0x0000000000000000000000000000000000000000   4   
skale-half-sturdy-denebola            0xa68F946090c600eDa6f139783077EE802Afeb990   16     43200      Oct 21 2024 11:31:24   0         2            0x0000000000000000000000000000000000000000   0   
unrealistic-wrong-dabih               0x47A260715623df37b9F5ea52C2E66245c0529DF2   16     43200      Oct 21 2024 17:57:00   0         2            0x0000000000000000000000000000000000000000   2   
minty-untimely-turais                 0x3279B8d8985d5F922e79b1e21a1833e35EF4A1FC   16     43200      Oct 21 2024 18:22:24   0         2            0x0000000000000000000000000000000000000000   3   
skale-brown-gripping-tania-borealis   0x487360568fE5Ee4AE5c75782D5F63e9935B0E512   16     43200      Oct 22 2024 14:48:00   0         2            0x0000000000000000000000000000000000000000   1   
```
