### ISSUE TITLE
Schain_record is not created in admin for newly created schain

### ISSUE THREAD

**Issue by OleksanderSalamatov** [skalenetwork/skale-admin#937]
After legacy network cleanup from schains and downgrade to 2.0 versions we tried to create new schain and encountered issue, when process manager in admin fails because of `error 'NoneType' object has no attribute 'monitor_last_seen'` in `process_manager_helper.py`. Seems like admin did not create schain_record for new chain

Versions: 
admin: 2.3.10 
skale-manager contract: 1.9.2-stable.0
skale-node branch: [legacy-2.1.13](https://github.com/skalenetwork/skale-node/tree/legacy-2.1.13)

Preconditions:
7 schains on nodes

Steps:
1) Remove all chains from network
2) Downgrade skale-components versions to 2.1.12 versions
3) Try to create schain and monitor logs on one of the nodes admin in group

Expected result:
Schain_record created, DKG process started

Actual result:
Scain_record not created, process manager failed, DKG not started

```
[2023-03-30 18:54:59,547 INFO] - 1 - MainThread - core.schains.process_manager_helper:90 - dkg_timeout: 1800, TIMEOUT_COEFFICIENT: 2.2, allowed_diff: 3960
[2023-03-30 18:54:59,548 ERROR] - 1 - MainThread - __main__:57 - Process manager procedure failed!
Traceback (most recent call last):
  File "admin.py", line 55, in monitor
    run_process_manager(skale, skale_ima, node_config)
  File "/usr/src/admin/core/schains/process_manager.py", line 68, in run_process_manager
    terminate_stuck_schain_process(skale, schain_record, schain)
  File "/usr/src/admin/core/schains/process_manager_helper.py", line 43, in terminate_stuck_schain_process
    if not schain_record.monitor_last_seen:
AttributeError: 'NoneType' object has no attribute 'monitor_last_seen'
[2023-03-30 18:54:59,548 INFO] - 1 - MainThread - __main__:58 - Sleeping for 90s after run_process_manager
```

Temporary solution to this, is to delete .skale/node_data/skale.db and restart admins on all nodes

**Comment by badrogger** [comment]
Potentially related to downgrade from 2.4.x -> 2.3.0 admin. 
Also it's nice to add more logs in skale_admin to show error at least in debug.

**Comment by OleksanderSalamatov** [comment]
More logs:
```
Monitoring sChains
Node ID: 1
sChains on node: []
Number of sChains on node: 0
Empty sChain structs: 6
====================================================================================================

[2023-03-30 18:45:44,792 INFO] - 1 - MainThread - core.schains.process_manager:84 - Creator procedure finished
[2023-03-30 18:45:44,792 INFO] - 1 - MainThread - __main__:58 - Sleeping for 90s after run_process_manager
[2023-03-30 18:47:14,863 INFO] - 1 - MainThread - core.schains.cleaner:63 - Cleaner process started
[2023-03-30 18:47:14,866 INFO] - 2586 - MainThread - tools.docker_utils:85 - Initing docker client with host unix:///var/run/skale/docker.sock
[2023-03-30 18:47:14,869 INFO] - 2586 - MainThread - core.schains.cleaner:108 - Cleaner procedure started.
[2023-03-30 18:47:15,084 INFO] - 2586 - MainThread - core.schains.cleaner:114 -
sChains on contracts: ['', '', '', '', '', '']
sChains on node: []
[2023-03-30 18:47:15,084 INFO] - 2586 - MainThread - core.schains.cleaner:130 - Cleanup procedure finished
[2023-03-30 18:47:15,089 INFO] - 1 - MainThread - core.schains.cleaner:65 - Cleaner process is joined.
[2023-03-30 18:47:15,089 INFO] - 1 - MainThread - core.schains.cleaner:66 - Terminating the process
[2023-03-30 18:47:15,089 INFO] - 1 - MainThread - __main__:63 - Sleeping for 90s after run_cleaner
[2023-03-30 18:48:45,127 INFO] - 1 - MainThread - core.schains.process_manager:57 - Process manager started
[2023-03-30 18:48:45,157 INFO] - 1 - MainThread - core.schains.notifications:35 - Node account has 219769933915522659 WEI
[2023-03-30 18:48:45,158 INFO] - 1 - MainThread - tools.notifications.messages:189 - Saving new balance state 137 1
[2023-03-30 18:48:45,158 INFO] - 1 - MainThread - core.schains.process_manager:91 - Fetching schains to monitor...
[2023-03-30 18:48:45,380 INFO] - 1 - MainThread - core.schains.process_manager:105 - Get leaving_history for node ...
[2023-03-30 18:48:45,401 INFO] - 1 - MainThread - core.schains.process_manager:113 - Got leaving sChains for the node: []
[2023-03-30 18:48:45,402 INFO] - 1 - MainThread - core.schains.process_manager:97 -
====================================================================================================
Monitoring sChains
Node ID: 1
sChains on node: []
Number of sChains on node: 0
Empty sChain structs: 6
====================================================================================================

[2023-03-30 18:48:45,402 INFO] - 1 - MainThread - core.schains.process_manager:84 - Creator procedure finished
[2023-03-30 18:48:45,402 INFO] - 1 - MainThread - __main__:58 - Sleeping for 90s after run_process_manager
[2023-03-30 18:50:15,486 INFO] - 1 - MainThread - core.schains.cleaner:63 - Cleaner process started
[2023-03-30 18:50:15,490 INFO] - 2606 - MainThread - tools.docker_utils:85 - Initing docker client with host unix:///var/run/skale/docker.sock
[2023-03-30 18:50:15,495 INFO] - 2606 - MainThread - core.schains.cleaner:108 - Cleaner procedure started.
[2023-03-30 18:50:15,671 INFO] - 2606 - MainThread - core.schains.cleaner:114 -
sChains on contracts: ['', 'fussy-smoggy-megrez', '', '', '', '']
sChains on node: []
[2023-03-30 18:50:15,671 INFO] - 2606 - MainThread - core.schains.cleaner:130 - Cleanup procedure finished
[2023-03-30 18:50:15,675 INFO] - 1 - MainThread - core.schains.cleaner:65 - Cleaner process is joined.
[2023-03-30 18:50:15,675 INFO] - 1 - MainThread - core.schains.cleaner:66 - Terminating the process
[2023-03-30 18:50:15,676 INFO] - 1 - MainThread - __main__:63 - Sleeping for 90s after run_cleaner
[2023-03-30 18:51:45,766 INFO] - 1 - MainThread - core.schains.process_manager:57 - Process manager started
[2023-03-30 18:51:45,779 INFO] - 1 - MainThread - core.schains.notifications:35 - Node account has 219769933915522659 WEI
[2023-03-30 18:51:45,779 INFO] - 1 - MainThread - tools.notifications.messages:189 - Saving new balance state 138 1
[2023-03-30 18:51:45,780 INFO] - 1 - MainThread - core.schains.process_manager:91 - Fetching schains to monitor...
[2023-03-30 18:51:45,948 INFO] - 1 - MainThread - core.schains.process_manager:105 - Get leaving_history for node ...
[2023-03-30 18:51:45,964 INFO] - 1 - MainThread - core.schains.process_manager:113 - Got leaving sChains for the node: []
[2023-03-30 18:51:45,964 INFO] - 1 - MainThread - core.schains.process_manager:97 -
====================================================================================================
Monitoring sChains
Node ID: 1
sChains on node: [{'name': 'fussy-smoggy-megrez', 'mainnetOwner': '0x487360568fE5Ee4AE5c75782D5F63e9935B0E512', 'indexInOwnerList': 0, 'partOfNode': 16, 'lifetime': 43200, 'startDate': 1680202188, 'startBlock': 8745472, 'deposit': 0, 'index': 0, 'generation': 1, 'originator': '0x0000000000000000000000000000000000000000', 'chainId': '0x000002670f8a5', 'multitransactionMode': True, 'thresholdEncryption': False, 'active': True}]
Number of sChains on node: 1
Empty sChain structs: 5
====================================================================================================

[2023-03-30 18:51:45,967 ERROR] - 1 - MainThread - web.models.schain:213 - schain_record is None for fussy-smoggy-megrez
[2023-03-30 18:51:46,012 INFO] - 1 - MainThread - core.schains.process_manager_helper:90 - dkg_timeout: 1800, TIMEOUT_COEFFICIENT: 2.2, allowed_diff: 3960
[2023-03-30 18:51:46,013 ERROR] - 1 - MainThread - __main__:57 - Process manager procedure failed!
Traceback (most recent call last):
  File "admin.py", line 55, in monitor
    run_process_manager(skale, skale_ima, node_config)
  File "/usr/src/admin/core/schains/process_manager.py", line 68, in run_process_manager
    terminate_stuck_schain_process(skale, schain_record, schain)
  File "/usr/src/admin/core/schains/process_manager_helper.py", line 43, in terminate_stuck_schain_process
    if not schain_record.monitor_last_seen:
AttributeError: 'NoneType' object has no attribute 'monitor_last_seen'
[2023-03-30 18:51:46,013 INFO] - 1 - MainThread - __main__:58 - Sleeping for 90s after run_process_manager
[2023-03-30 18:53:16,106 INFO] - 1 - MainThread - core.schains.cleaner:63 - Cleaner process started
[2023-03-30 18:53:16,109 INFO] - 2625 - MainThread - tools.docker_utils:85 - Initing docker client with host unix:///var/run/skale/docker.sock
[2023-03-30 18:53:16,112 INFO] - 2625 - MainThread - core.schains.cleaner:108 - Cleaner procedure started.
[2023-03-30 18:53:16,303 INFO] - 2625 - MainThread - core.schains.cleaner:114 -
sChains on contracts: ['', 'fussy-smoggy-megrez', '', '', '', '']
sChains on node: []
[2023-03-30 18:53:16,304 INFO] - 2625 - MainThread - core.schains.cleaner:130 - Cleanup procedure finished
[2023-03-30 18:53:16,308 INFO] - 1 - MainThread - core.schains.cleaner:65 - Cleaner process is joined.
[2023-03-30 18:53:16,308 INFO] - 1 - MainThread - core.schains.cleaner:66 - Terminating the process
[2023-03-30 18:53:16,309 INFO] - 1 - MainThread - __main__:63 - Sleeping for 90s after run_cleaner
[2023-03-30 18:54:46,335 INFO] - 1 - MainThread - core.schains.process_manager:57 - Process manager started
[2023-03-30 18:54:46,350 INFO] - 1 - MainThread - core.schains.notifications:35 - Node account has 219769933915522659 WEI
[2023-03-30 18:54:46,351 INFO] - 1 - MainThread - tools.notifications.messages:189 - Saving new balance state 139 1
[2023-03-30 18:54:46,351 INFO] - 1 - MainThread - core.schains.process_manager:91 - Fetching schains to monitor...
[2023-03-30 18:54:46,532 INFO] - 1 - MainThread - core.schains.process_manager:105 - Get leaving_history for node ...
[2023-03-30 18:54:46,553 INFO] - 1 - MainThread - core.schains.process_manager:113 - Got leaving sChains for the node: []
[2023-03-30 18:54:46,556 INFO] - 1 - MainThread - core.schains.process_manager:97 -
====================================================================================================
Monitoring sChains
Node ID: 1
sChains on node: [{'name': 'fussy-smoggy-megrez', 'mainnetOwner': '0x487360568fE5Ee4AE5c75782D5F63e9935B0E512', 'indexInOwnerList': 0, 'partOfNode': 16, 'lifetime': 43200, 'startDate': 1680202188, 'startBlock': 8745472, 'deposit': 0, 'index': 0, 'generation': 1, 'originator': '0x0000000000000000000000000000000000000000', 'chainId': '0x000002670f8a5', 'multitransactionMode': True, 'thresholdEncryption': False, 'active': True}]
Number of sChains on node: 1
Empty sChain structs: 5
====================================================================================================

[2023-03-30 18:54:46,560 ERROR] - 1 - MainThread - web.models.schain:213 - schain_record is None for fussy-smoggy-megrez
[2023-03-30 18:54:46,578 INFO] - 1 - MainThread - core.schains.process_manager_helper:90 - dkg_timeout: 1800, TIMEOUT_COEFFICIENT: 2.2, allowed_diff: 3960
[2023-03-30 18:54:46,579 ERROR] - 1 - MainThread - __main__:57 - Process manager procedure failed!
Traceback (most recent call last):
  File "admin.py", line 55, in monitor
    run_process_manager(skale, skale_ima, node_config)
  File "/usr/src/admin/core/schains/process_manager.py", line 68, in run_process_manager
    terminate_stuck_schain_process(skale, schain_record, schain)
  File "/usr/src/admin/core/schains/process_manager_helper.py", line 43, in terminate_stuck_schain_process
    if not schain_record.monitor_last_seen:
AttributeError: 'NoneType' object has no attribute 'monitor_last_seen'
[2023-03-30 18:54:46,579 INFO] - 1 - MainThread - __main__:58 - Sleeping for 90s after run_process_manager
[2023-03-30 18:56:16,621 INFO] - 1 - MainThread - core.schains.cleaner:63 - Cleaner process started
[2023-03-30 18:56:16,624 INFO] - 2644 - MainThread - tools.docker_utils:85 - Initing docker client with host unix:///var/run/skale/docker.sock
[2023-03-30 18:56:16,629 INFO] - 2644 - MainThread - core.schains.cleaner:108 - Cleaner procedure started.
[2023-03-30 18:56:16,874 INFO] - 2644 - MainThread - core.schains.cleaner:114 -
sChains on contracts: ['', 'fussy-smoggy-megrez', '', '', '', '']
sChains on node: []
[2023-03-30 18:56:16,874 INFO] - 2644 - MainThread - core.schains.cleaner:130 - Cleanup procedure finished
[2023-03-30 18:56:16,878 INFO] - 1 - MainThread - core.schains.cleaner:65 - Cleaner process is joined.
[2023-03-30 18:56:16,878 INFO] - 1 - MainThread - core.schains.cleaner:66 - Terminating the process
[2023-03-30 18:56:16,879 INFO] - 1 - MainThread - __main__:63 - Sleeping for 90s after run_cleaner
[2023-03-30 18:57:46,917 INFO] - 1 - MainThread - core.schains.process_manager:57 - Process manager started
[2023-03-30 18:57:46,935 INFO] - 1 - MainThread - core.schains.notifications:35 - Node account has 219769933915522659 WEI
[2023-03-30 18:57:46,937 INFO] - 1 - MainThread - tools.notifications.messages:189 - Saving new balance state 140 1
[2023-03-30 18:57:46,938 INFO] - 1 - MainThread - core.schains.process_manager:91 - Fetching schains to monitor...
[2023-03-30 18:57:47,142 INFO] - 1 - MainThread - core.schains.process_manager:105 - Get leaving_history for node ...
[2023-03-30 18:57:47,158 INFO] - 1 - MainThread - core.schains.process_manager:113 - Got leaving sChains for the node: []
[2023-03-30 18:57:47,158 INFO] - 1 - MainThread - core.schains.process_manager:97 -
====================================================================================================
Monitoring sChains
Node ID: 1
sChains on node: [{'name': 'fussy-smoggy-megrez', 'mainnetOwner': '0x487360568fE5Ee4AE5c75782D5F63e9935B0E512', 'indexInOwnerList': 0, 'partOfNode': 16, 'lifetime': 43200, 'startDate': 1680202188, 'startBlock': 8745472, 'deposit': 0, 'index': 0, 'generation': 1, 'originator': '0x0000000000000000000000000000000000000000', 'chainId': '0x000002670f8a5', 'multitransactionMode': True, 'thresholdEncryption': False, 'active': True}]
Number of sChains on node: 1
Empty sChain structs: 5
====================================================================================================

[2023-03-30 18:57:47,161 ERROR] - 1 - MainThread - web.models.schain:213 - schain_record is None for fussy-smoggy-megrez
[2023-03-30 18:57:47,176 INFO] - 1 - MainThread - core.schains.process_manager_helper:90 - dkg_timeout: 1800, TIMEOUT_COEFFICIENT: 2.2, allowed_diff: 3960
[2023-03-30 18:57:47,176 ERROR] - 1 - MainThread - __main__:57 - Process manager procedure failed!
Traceback (most recent call last):
  File "admin.py", line 55, in monitor
    run_process_manager(skale, skale_ima, node_config)
  File "/usr/src/admin/core/schains/process_manager.py", line 68, in run_process_manager
    terminate_stuck_schain_process(skale, schain_record, schain)
  File "/usr/src/admin/core/schains/process_manager_helper.py", line 43, in terminate_stuck_schain_process
    if not schain_record.monitor_last_seen:
AttributeError: 'NoneType' object has no attribute 'monitor_last_seen'
[2023-03-30 18:57:47,177 INFO] - 1 - MainThread - __main__:58 - Sleeping for 90s after run_process_manager
[2023-03-30 18:59:17,202 INFO] - 1 - MainThread - core.schains.cleaner:63 - Cleaner process started
[2023-03-30 18:59:17,205 INFO] - 2663 - MainThread - tools.docker_utils:85 - Initing docker client with host unix:///var/run/skale/docker.sock
[2023-03-30 18:59:17,209 INFO] - 2663 - MainThread - core.schains.cleaner:108 - Cleaner procedure started.
[2023-03-30 18:59:17,392 INFO] - 2663 - MainThread - core.schains.cleaner:114 -
sChains on contracts: ['', 'fussy-smoggy-megrez', '', '', '', '']
sChains on node: []
[2023-03-30 18:59:17,392 INFO] - 2663 - MainThread - core.schains.cleaner:130 - Cleanup procedure finished
[2023-03-30 18:59:17,397 INFO] - 1 - MainThread - core.schains.cleaner:65 - Cleaner process is joined.
[2023-03-30 18:59:17,397 INFO] - 1 - MainThread - core.schains.cleaner:66 - Terminating the process
[2023-03-30 18:59:17,397 INFO] - 1 - MainThread - __main__:63 - Sleeping for 90s after run_cleaner
[2023-03-30 19:00:47,419 INFO] - 1 - MainThread - core.schains.process_manager:57 - Process manager started
[2023-03-30 19:00:47,437 INFO] - 1 - MainThread - core.schains.notifications:35 - Node account has 219769933915522659 WEI
[2023-03-30 19:00:47,438 INFO] - 1 - MainThread - tools.notifications.messages:189 - Saving new balance state 141 1
[2023-03-30 19:00:47,438 INFO] - 1 - MainThread - core.schains.process_manager:91 - Fetching schains to monitor...
[2023-03-30 19:00:47,813 INFO] - 1 - MainThread - core.schains.process_manager:105 - Get leaving_history for node ...
[2023-03-30 19:00:47,843 INFO] - 1 - MainThread - core.schains.process_manager:113 - Got leaving sChains for the node: []
```
