### ISSUE TITLE
Parsing broadcast events process is failed 

### ISSUE THREAD

**Issue by yatsunastya** [skalenetwork/skale-admin#971]
**Describe the bug**
1. Node receives 15 broadcasts from other nodes in the group 
```
[2023-09-03 11:00:24,943 INFO][12][curly-red-alterf][T_1] - core.schains.dkg.utils:137 - sChain curly-red-alterf: total received 15 broadcasts from nodes [35, 9, 29, 15, 25, 31, 24, 16, 20, 23, 11, 17, 28, 19, 57]
```
2. Node tries to parse broadcast events from blocks
```
[2023-09-03 11:01:06,791 INFO][12][curly-red-alterf][T_1] - core.schains.dkg.broadcast_filter:94 - sChain 0x000001fe6cdfae2691fe53493e697d4172434e71011784f660d5f407ffbb7100: Parsing broadcast events from 9629305 block to 9629318 block
```
3. Broadcast events process is failed 
```
[2023-09-03 11:01:36,124 ERROR][12][curly-red-alterf][T_1] - core.schains.task:26 - Task curly-red-alterf-config failed with {'code': -32002, 'message': 'No response or no available upstream for eth_getBlockByNumber'}
Traceback (most recent call last):
  File "/usr/src/admin/core/schains/task.py", line 24, in run
    self.action()
  File "/usr/src/admin/core/schains/monitor/main.py", line 105, in run_config_pipeline
    mon.run()
  File "/usr/src/admin/core/schains/monitor/config_monitor.py", line 48, in run
    self.execute()
  File "/usr/src/admin/core/schains/monitor/config_monitor.py", line 59, in execute
    self.am.dkg()
  File "/usr/src/admin/core/schains/monitor/action.py", line 96, in _monitor_block
    initial_status = f(self, *args, **kwargs)
  File "/usr/src/admin/core/schains/monitor/action.py", line 169, in dkg
    dkg_result = safe_run_dkg(
  File "/usr/src/admin/core/schains/dkg/main.py", line 169, in safe_run_dkg
    init_bls(dkg_client, node_id, sgx_key_name, rotation_id)
  File "/usr/src/admin/core/schains/dkg/main.py", line 59, in init_bls
    broadcast_and_check_data(dkg_client)
  File "/usr/src/admin/core/schains/dkg/utils.py", line 110, in broadcast_and_check_data
    events = dkg_filter.get_events()
  File "/usr/src/admin/core/schains/dkg/broadcast_filter.py", line 98, in get_events
    block = self.skale.web3.eth.get_block(block_number, full_transactions=True)
  File "/usr/local/lib/python3.9/site-packages/web3/eth/eth.py", line 389, in get_block
    return self._get_block(block_identifier, full_transactions)
  File "/usr/local/lib/python3.9/site-packages/web3/module.py", line 68, in caller
    result = w3.manager.request_blocking(
  File "/usr/local/lib/python3.9/site-packages/web3/manager.py", line 232, in request_blocking
    return self.formatted_response(
  File "/usr/local/lib/python3.9/site-packages/web3/manager.py", line 205, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32002, 'message': 'No response or no available upstream for eth_getBlockByNumber'}
```
4. As a result it prevents getting aftercoming broadcasts/alrights

Admin: 2.5.1-develop.4
[admin_dkg.txt](https://github.com/skalenetwork/skale-admin/files/12515514/admin_dkg.txt)

**Comment by olehnikolaiev** [comment]
the problem is related to the incorrect geth behavior (probably network issues). pr will not fix them but will prevent dkg process from crashing after getting such errors

**Comment by DmytroNazarenko** [comment]
skale-admin: 2.6.0-beta.0

**Comment by yatsunastya** [comment]
admin: `2.6.0-beta.0`

Steps that were used in testing:
1. Start schain creation
2. Block connection from outgoing ports on geth node, once first `broadcasts` are sent 
3. Check admin logs on node which sent `broadcast` (expected :arrow_down: ) 
```
[2024-02-09 17:21:34,489 ERROR][81210][scornful-bruised-deneb-algedi][MainThread] - core.schains.monitor.main:270 - Monitor iteration failed
Traceback (most recent call last):
  File "/usr/src/admin/core/schains/monitor/main.py", line 255, in run_monitor_for_schain
    create_and_execute_tasks(
  File "/usr/src/admin/core/schains/monitor/main.py", line 190, in create_and_execute_tasks
    is_rotation_active = skale.node_rotation.is_rotation_active(name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/skale/contracts/manager/node_rotation.py", line 102, in is_rotation_active
    finish_ts_reached = self.is_finish_ts_reached(schain_name)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/skale/contracts/manager/node_rotation.py", line 106, in is_finish_ts_reached
    rotation = self.skale.node_rotation.get_rotation_obj(schain_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/skale/contracts/manager/node_rotation.py", line 55, in get_rotation_obj
    rotation_data = self.contract.functions.getRotation(schain_id).call()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/contract/contract.py", line 305, in call
    return call_contract_function(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/contract/utils.py", line 96, in call_contract_function
    return_data = w3.eth.call(
                  ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/eth/eth.py", line 257, in call
    return self._durin_call(transaction, block_identifier, state_override)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/eth/eth.py", line 276, in _durin_call
    return self._call(transaction, block_identifier, state_override)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/module.py", line 75, in caller
    result = w3.manager.request_blocking(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/manager.py", line 324, in request_blocking
    response = self._make_request(method, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/manager.py", line 212, in _make_request
    return request_func(method, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/middleware/attrdict.py", line 43, in middleware
    response = make_request(method, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/skale/utils/web3_utils.py", line 116, in middleware
    raise EthClientOutdatedError(outdated_client_time_msg(
skale.utils.web3_utils.EthClientOutdatedError: eth_call failed; current_time: 1707499294.4896197, latest_block_timestamp: 1707498912, allowed_ts_diff: 300
```
4. Unblock connection from outgoing ports on geth node after complaint time limit
5. Check admin logs 

The issue wasn't reproduced. 
Due to complicated setting and low possibility on Mainnet, define it like unverifiable.
