### ISSUE TITLE
Admin`s monitor doesn't finish gracefully in case of failed rpc

### ISSUE THREAD

**Issue by yatsunastya** [skalenetwork/skale-admin#992]
**Describe the bug**
In case of failed rpc, when admin tries to set skaled exit time, error appears and it's not handled. So as a result `NewConfigSkaledMonitor` doesn't finish gracefully. 

**Version:**
admin - 2.5.1-develop.7

**To Reproduce**
1. Start node rotation
2. Disable loopback connection through skaled http port on one of staying nodes
3. Check admin's logs 
4. See error :arrow_down: 

```
[2023-10-06 11:47:02,320 INFO][9][skale-loving-somber-praecipua][T_0] - core.schains.monitor.action:423 - Trying to set skaled exit time 1696593384
[2023-10-06 11:47:02,323 INFO][9][skale-loving-somber-praecipua][T_0] - core.schains.rotation:37 - Sending rotation request: 1696593384
[2023-10-06 11:49:12,719 ERROR][9][skale-loving-somber-praecipua][T_0] - core.schains.task:26 - Task skale-loving-somber-praecipua-skaled failed with HTTPConnectionPool(host='127.0.0.1', port=10131): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fefb53eea90>: Failed to establish a new connection: [Errno 110] Connection timed out'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 168, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 233, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 199, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 180, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fefb53eea90>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=10131): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fefb53eea90>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/admin/core/schains/task.py", line 24, in run
    self.action()
  File "/usr/src/admin/core/schains/monitor/main.py", line 156, in run_skaled_pipeline
    mon(skaled_am, skaled_checks).run()
  File "/usr/src/admin/core/schains/monitor/skaled_monitor.py", line 53, in run
    self.execute()
  File "/usr/src/admin/core/schains/monitor/skaled_monitor.py", line 171, in execute
    self.am.send_exit_request()
  File "/usr/src/admin/core/schains/monitor/action.py", line 96, in _monitor_block
    initial_status = f(self, *args, **kwargs)
  File "/usr/src/admin/core/schains/monitor/action.py", line 427, in send_exit_request
    set_rotation_for_schain(url, finish_ts)
  File "/usr/src/admin/core/schains/rotation.py", line 33, in set_rotation_for_schain
    _send_rotation_request(url, timestamp)
  File "/usr/src/admin/core/schains/rotation.py", line 48, in _send_rotation_request
    response = requests.post(
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=10131): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fefb53eea90>: Failed to establish a new connection: [Errno 110] Connection timed out'))
[2023-10-06 11:49:12,730 INFO][9][skale-loving-somber-praecipua][T_0] - core.schains.task:27 - Sleeping after task execution for 2
```
[rpc_admin.txt](https://github.com/skalenetwork/skale-admin/files/12832988/rpc_admin.txt)

```[tasklist]
### Depends on
- [ ] https://github.com/skalenetwork/internal-support/issues/450
```

**Comment by DmytroNazarenko** [comment]
Added to 2.3 due to small size of fix and affection of node-rotation process

**Comment by PolinaKiporenko** [comment]
should be solved after https://github.com/skalenetwork/internal-support/issues/450

**Comment by badrogger** [comment]
This functionality was removed in 2.6.x skale-admin.

**Comment by DmytroNazarenko** [comment]
skale-admin: 2.6.0-beta.0

**Comment by yatsunastya** [comment]
Checked ✅
Admin: 2.6.0-beta.0 

As the functionality was removed, tested that `UpdateConfigSkaledMonitor` (previously `NewConfigSkaledMonitor`) monitor runs smoothly and no problems occur during node rotation procedure in skale-admin work.

```
[2024-01-31 12:54:15,682 INFO][8][alive-long-crafty-SKALE][T_1] - core.schains.monitor.skaled_monitor:51 - Skaled monitor type starting UpdateConfigSkaledMonitor
```
```
[2024-01-31 12:55:06,865 INFO][8][alive-long-crafty-SKALE][T_1] - core.schains.monitor.skaled_monitor:59 - Skaled monitor type finished UpdateConfigSkaledMonitor
```
